// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="systolic_array_systolic_array,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.268000,HLS_SYN_LAT=197,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=859,HLS_SYN_LUT=1874,HLS_VERSION=2021_1}" *)

module systolic_array (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_0_0,
        A_0_1,
        A_0_2,
        A_0_3,
        A_1_0,
        A_1_1,
        A_1_2,
        A_1_3,
        A_2_0,
        A_2_1,
        A_2_2,
        A_2_3,
        A_3_0,
        A_3_1,
        A_3_2,
        A_3_3,
        B_0_0,
        B_0_1,
        B_0_2,
        B_0_3,
        B_1_0,
        B_1_1,
        B_1_2,
        B_1_3,
        B_2_0,
        B_2_1,
        B_2_2,
        B_2_3,
        B_3_0,
        B_3_1,
        B_3_2,
        B_3_3,
        C_0_0,
        C_0_0_ap_vld,
        C_0_1,
        C_0_1_ap_vld,
        C_0_2,
        C_0_2_ap_vld,
        C_0_3,
        C_0_3_ap_vld,
        C_1_0,
        C_1_0_ap_vld,
        C_1_1,
        C_1_1_ap_vld,
        C_1_2,
        C_1_2_ap_vld,
        C_1_3,
        C_1_3_ap_vld,
        C_2_0,
        C_2_0_ap_vld,
        C_2_1,
        C_2_1_ap_vld,
        C_2_2,
        C_2_2_ap_vld,
        C_2_3,
        C_2_3_ap_vld,
        C_3_0,
        C_3_0_ap_vld,
        C_3_1,
        C_3_1_ap_vld,
        C_3_2,
        C_3_2_ap_vld,
        C_3_3,
        C_3_3_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] A_0_0;
input  [15:0] A_0_1;
input  [15:0] A_0_2;
input  [15:0] A_0_3;
input  [15:0] A_1_0;
input  [15:0] A_1_1;
input  [15:0] A_1_2;
input  [15:0] A_1_3;
input  [15:0] A_2_0;
input  [15:0] A_2_1;
input  [15:0] A_2_2;
input  [15:0] A_2_3;
input  [15:0] A_3_0;
input  [15:0] A_3_1;
input  [15:0] A_3_2;
input  [15:0] A_3_3;
input  [15:0] B_0_0;
input  [15:0] B_0_1;
input  [15:0] B_0_2;
input  [15:0] B_0_3;
input  [15:0] B_1_0;
input  [15:0] B_1_1;
input  [15:0] B_1_2;
input  [15:0] B_1_3;
input  [15:0] B_2_0;
input  [15:0] B_2_1;
input  [15:0] B_2_2;
input  [15:0] B_2_3;
input  [15:0] B_3_0;
input  [15:0] B_3_1;
input  [15:0] B_3_2;
input  [15:0] B_3_3;
output  [15:0] C_0_0;
output   C_0_0_ap_vld;
output  [15:0] C_0_1;
output   C_0_1_ap_vld;
output  [15:0] C_0_2;
output   C_0_2_ap_vld;
output  [15:0] C_0_3;
output   C_0_3_ap_vld;
output  [15:0] C_1_0;
output   C_1_0_ap_vld;
output  [15:0] C_1_1;
output   C_1_1_ap_vld;
output  [15:0] C_1_2;
output   C_1_2_ap_vld;
output  [15:0] C_1_3;
output   C_1_3_ap_vld;
output  [15:0] C_2_0;
output   C_2_0_ap_vld;
output  [15:0] C_2_1;
output   C_2_1_ap_vld;
output  [15:0] C_2_2;
output   C_2_2_ap_vld;
output  [15:0] C_2_3;
output   C_2_3_ap_vld;
output  [15:0] C_3_0;
output   C_3_0_ap_vld;
output  [15:0] C_3_1;
output   C_3_1_ap_vld;
output  [15:0] C_3_2;
output   C_3_2_ap_vld;
output  [15:0] C_3_3;
output   C_3_3_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_0_0_ap_vld;
reg C_0_1_ap_vld;
reg C_0_2_ap_vld;
reg C_0_3_ap_vld;
reg C_1_0_ap_vld;
reg C_1_1_ap_vld;
reg C_1_2_ap_vld;
reg C_1_3_ap_vld;
reg C_2_0_ap_vld;
reg C_2_1_ap_vld;
reg C_2_2_ap_vld;
reg C_2_3_ap_vld;
reg C_3_0_ap_vld;
reg C_3_1_ap_vld;
reg C_3_2_ap_vld;
reg C_3_3_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] add_ln25_fu_1136_p2;
reg   [4:0] add_ln25_reg_2088;
wire    ap_CS_fsm_state4;
wire   [2:0] select_ln25_fu_1202_p3;
reg   [2:0] select_ln25_reg_2093;
wire   [0:0] icmp_ln25_fu_1130_p2;
wire   [2:0] select_ln25_1_fu_1216_p3;
reg   [2:0] select_ln25_1_reg_2098;
wire   [1:0] trunc_ln25_fu_1224_p1;
reg   [1:0] trunc_ln25_reg_2103;
wire   [1:0] empty_10_fu_1229_p1;
reg   [1:0] empty_10_reg_2108;
wire   [15:0] tmp_fu_1246_p18;
reg   [15:0] tmp_reg_2113;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_done;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_idle;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_ready;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_0_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_3_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_3_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_2_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_2_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_1_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_1_1_out_ap_vld;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_0_1_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_0_1_out_ap_vld;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_done;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_idle;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_ready;
wire   [15:0] grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
wire    grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out_ap_vld;
reg    grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [2:0] j_fu_156;
wire   [2:0] add_ln26_fu_1384_p2;
wire    ap_CS_fsm_state6;
reg   [2:0] i_fu_160;
reg   [4:0] indvar_flatten7_fu_164;
reg   [15:0] buffer_V_0_0_4_fu_168;
wire    ap_CS_fsm_state3;
reg   [15:0] buffer_V_0_1_4_fu_172;
reg   [15:0] buffer_V_0_2_4_fu_176;
reg   [15:0] buffer_V_0_3_4_fu_180;
reg   [15:0] buffer_V_1_0_4_fu_184;
reg   [15:0] buffer_V_1_1_4_fu_188;
reg   [15:0] buffer_V_1_2_4_fu_192;
reg   [15:0] buffer_V_1_3_4_fu_196;
reg   [15:0] buffer_V_2_0_4_fu_200;
reg   [15:0] buffer_V_2_1_4_fu_204;
reg   [15:0] buffer_V_2_2_4_fu_208;
reg   [15:0] buffer_V_2_3_4_fu_212;
reg   [15:0] buffer_V_3_0_4_fu_216;
reg   [15:0] buffer_V_3_1_4_fu_220;
reg   [15:0] buffer_V_3_2_4_fu_224;
reg   [15:0] buffer_V_3_3_4_fu_228;
wire   [0:0] icmp_ln26_fu_1196_p2;
wire   [2:0] add_ln25_1_fu_1210_p2;
wire   [3:0] tmp_3_fu_1234_p3;
wire   [4:0] tmp_fu_1246_p17;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start_reg = 1'b0;
#0 grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start_reg = 1'b0;
end

systolic_array_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2 grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start),
    .ap_done(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_done),
    .ap_idle(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_idle),
    .ap_ready(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_ready),
    .local_A_V_3_0(A_3_3),
    .local_A_V_3_0_4(A_3_2),
    .local_A_V_3_0_3(A_3_1),
    .local_A_V_3_0_13(A_2_3),
    .local_A_V_3_0_16(A_2_2),
    .local_A_V_3_0_15(A_2_1),
    .local_A_V_3_0_9(A_1_3),
    .local_A_V_3_0_12(A_1_2),
    .local_A_V_3_0_11(A_1_1),
    .local_A_V_3_0_5(A_0_3),
    .local_A_V_3_0_8(A_0_2),
    .local_A_V_3_0_7(A_0_1),
    .local_A_V_3_0_2(A_3_0),
    .local_A_V_3_0_14(A_2_0),
    .local_A_V_3_0_10(A_1_0),
    .local_A_V_3_0_6(A_0_0),
    .B_3_3_load(B_3_3),
    .B_3_2_load(B_3_2),
    .B_3_1_load(B_3_1),
    .B_2_3_load(B_2_3),
    .B_2_2_load(B_2_2),
    .B_2_1_load(B_2_1),
    .B_1_3_load(B_1_3),
    .B_1_2_load(B_1_2),
    .B_1_1_load(B_1_1),
    .B_0_3_load(B_0_3),
    .B_0_2_load(B_0_2),
    .B_0_1_load(B_0_1),
    .B_3_0_load(B_3_0),
    .B_2_0_load(B_2_0),
    .B_1_0_load(B_1_0),
    .B_0_0_load(B_0_0),
    .buffer_V_3_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_3_1_out),
    .buffer_V_3_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_3_1_out_ap_vld),
    .buffer_V_3_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_2_1_out),
    .buffer_V_3_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_2_1_out_ap_vld),
    .buffer_V_3_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_1_1_out),
    .buffer_V_3_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_1_1_out_ap_vld),
    .buffer_V_3_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_0_1_out),
    .buffer_V_3_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_0_1_out_ap_vld),
    .buffer_V_2_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_3_1_out),
    .buffer_V_2_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_3_1_out_ap_vld),
    .buffer_V_2_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_2_1_out),
    .buffer_V_2_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_2_1_out_ap_vld),
    .buffer_V_2_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_1_1_out),
    .buffer_V_2_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_1_1_out_ap_vld),
    .buffer_V_2_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_0_1_out),
    .buffer_V_2_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_0_1_out_ap_vld),
    .buffer_V_1_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_3_1_out),
    .buffer_V_1_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_3_1_out_ap_vld),
    .buffer_V_1_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_2_1_out),
    .buffer_V_1_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_2_1_out_ap_vld),
    .buffer_V_1_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_1_1_out),
    .buffer_V_1_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_1_1_out_ap_vld),
    .buffer_V_1_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_0_1_out),
    .buffer_V_1_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_0_1_out_ap_vld),
    .buffer_V_0_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_3_1_out),
    .buffer_V_0_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_3_1_out_ap_vld),
    .buffer_V_0_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_2_1_out),
    .buffer_V_0_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_2_1_out_ap_vld),
    .buffer_V_0_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_1_1_out),
    .buffer_V_0_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_1_1_out_ap_vld),
    .buffer_V_0_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_0_1_out),
    .buffer_V_0_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_0_1_out_ap_vld),
    .local_B_V_3_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_3_1_out),
    .local_B_V_3_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_3_1_out_ap_vld),
    .local_B_V_3_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_2_1_out),
    .local_B_V_3_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_2_1_out_ap_vld),
    .local_B_V_3_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_1_1_out),
    .local_B_V_3_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_1_1_out_ap_vld),
    .local_B_V_3_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_0_1_out),
    .local_B_V_3_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_0_1_out_ap_vld),
    .local_B_V_2_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_3_1_out),
    .local_B_V_2_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_3_1_out_ap_vld),
    .local_B_V_2_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_2_1_out),
    .local_B_V_2_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_2_1_out_ap_vld),
    .local_B_V_2_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_1_1_out),
    .local_B_V_2_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_1_1_out_ap_vld),
    .local_B_V_2_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_0_1_out),
    .local_B_V_2_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_0_1_out_ap_vld),
    .local_B_V_1_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_3_1_out),
    .local_B_V_1_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_3_1_out_ap_vld),
    .local_B_V_1_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_2_1_out),
    .local_B_V_1_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_2_1_out_ap_vld),
    .local_B_V_1_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_1_1_out),
    .local_B_V_1_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_1_1_out_ap_vld),
    .local_B_V_1_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_0_1_out),
    .local_B_V_1_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_0_1_out_ap_vld),
    .local_B_V_0_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_3_1_out),
    .local_B_V_0_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_3_1_out_ap_vld),
    .local_B_V_0_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_2_1_out),
    .local_B_V_0_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_2_1_out_ap_vld),
    .local_B_V_0_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_1_1_out),
    .local_B_V_0_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_1_1_out_ap_vld),
    .local_B_V_0_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_0_1_out),
    .local_B_V_0_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_0_1_out_ap_vld),
    .local_A_V_3_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_3_1_out),
    .local_A_V_3_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_3_1_out_ap_vld),
    .local_A_V_3_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_2_1_out),
    .local_A_V_3_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_2_1_out_ap_vld),
    .local_A_V_3_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_1_1_out),
    .local_A_V_3_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_1_1_out_ap_vld),
    .local_A_V_3_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_0_1_out),
    .local_A_V_3_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_0_1_out_ap_vld),
    .local_A_V_2_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_3_1_out),
    .local_A_V_2_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_3_1_out_ap_vld),
    .local_A_V_2_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_2_1_out),
    .local_A_V_2_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_2_1_out_ap_vld),
    .local_A_V_2_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_1_1_out),
    .local_A_V_2_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_1_1_out_ap_vld),
    .local_A_V_2_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_0_1_out),
    .local_A_V_2_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_0_1_out_ap_vld),
    .local_A_V_1_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_3_1_out),
    .local_A_V_1_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_3_1_out_ap_vld),
    .local_A_V_1_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_2_1_out),
    .local_A_V_1_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_2_1_out_ap_vld),
    .local_A_V_1_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_1_1_out),
    .local_A_V_1_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_1_1_out_ap_vld),
    .local_A_V_1_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_0_1_out),
    .local_A_V_1_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_0_1_out_ap_vld),
    .local_A_V_0_3_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_3_1_out),
    .local_A_V_0_3_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_3_1_out_ap_vld),
    .local_A_V_0_2_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_2_1_out),
    .local_A_V_0_2_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_2_1_out_ap_vld),
    .local_A_V_0_1_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_1_1_out),
    .local_A_V_0_1_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_1_1_out_ap_vld),
    .local_A_V_0_0_1_out(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_0_1_out),
    .local_A_V_0_0_1_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_0_1_out_ap_vld)
);

systolic_array_systolic_array_Pipeline_VITIS_LOOP_27_5 grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start),
    .ap_done(grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_done),
    .ap_idle(grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_idle),
    .ap_ready(grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_ready),
    .tmp(tmp_reg_2113),
    .i_1_t33_mid2(trunc_ln25_reg_2103),
    .local_A_V_0_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_0_1_out),
    .local_A_V_0_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_1_1_out),
    .local_A_V_0_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_2_1_out),
    .local_A_V_0_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_0_3_1_out),
    .local_A_V_1_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_0_1_out),
    .local_A_V_1_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_1_1_out),
    .local_A_V_1_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_2_1_out),
    .local_A_V_1_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_1_3_1_out),
    .local_A_V_2_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_0_1_out),
    .local_A_V_2_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_1_1_out),
    .local_A_V_2_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_2_1_out),
    .local_A_V_2_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_2_3_1_out),
    .local_A_V_3_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_0_1_out),
    .local_A_V_3_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_1_1_out),
    .local_A_V_3_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_2_1_out),
    .local_A_V_3_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_A_V_3_3_1_out),
    .j_1_t(empty_10_reg_2108),
    .local_B_V_0_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_0_1_out),
    .local_B_V_0_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_1_1_out),
    .local_B_V_0_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_2_1_out),
    .local_B_V_0_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_0_3_1_out),
    .local_B_V_1_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_0_1_out),
    .local_B_V_1_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_1_1_out),
    .local_B_V_1_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_2_1_out),
    .local_B_V_1_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_1_3_1_out),
    .local_B_V_2_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_0_1_out),
    .local_B_V_2_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_1_1_out),
    .local_B_V_2_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_2_1_out),
    .local_B_V_2_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_2_3_1_out),
    .local_B_V_3_0_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_0_1_out),
    .local_B_V_3_1_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_1_1_out),
    .local_B_V_3_2_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_2_1_out),
    .local_B_V_3_3_1_reload(grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_local_B_V_3_3_1_out),
    .buffer_V_3_0_out(grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out),
    .buffer_V_3_0_out_ap_vld(grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out_ap_vld)
);

systolic_array_mux_165_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
mux_165_16_1_1_U122(
    .din0(buffer_V_0_0_4_fu_168),
    .din1(buffer_V_0_1_4_fu_172),
    .din2(buffer_V_0_2_4_fu_176),
    .din3(buffer_V_0_3_4_fu_180),
    .din4(buffer_V_1_0_4_fu_184),
    .din5(buffer_V_1_1_4_fu_188),
    .din6(buffer_V_1_2_4_fu_192),
    .din7(buffer_V_1_3_4_fu_196),
    .din8(buffer_V_2_0_4_fu_200),
    .din9(buffer_V_2_1_4_fu_204),
    .din10(buffer_V_2_2_4_fu_208),
    .din11(buffer_V_2_3_4_fu_212),
    .din12(buffer_V_3_0_4_fu_216),
    .din13(buffer_V_3_1_4_fu_220),
    .din14(buffer_V_3_2_4_fu_224),
    .din15(buffer_V_3_3_4_fu_228),
    .din16(tmp_fu_1246_p17),
    .dout(tmp_fu_1246_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start_reg <= 1'b1;
        end else if ((grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_ready == 1'b1)) begin
            grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln25_fu_1130_p2 == 1'd0))) begin
            grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start_reg <= 1'b1;
        end else if ((grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_ready == 1'b1)) begin
            grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_0_0_4_fu_168 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_0_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd0) & (trunc_ln25_reg_2103 == 2'd0))) begin
        buffer_V_0_0_4_fu_168 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_0_1_4_fu_172 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_1_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd1) & (trunc_ln25_reg_2103 == 2'd0))) begin
        buffer_V_0_1_4_fu_172 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_0_2_4_fu_176 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_2_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd2) & (trunc_ln25_reg_2103 == 2'd0))) begin
        buffer_V_0_2_4_fu_176 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_0_3_4_fu_180 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_0_3_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd3) & (trunc_ln25_reg_2103 == 2'd0))) begin
        buffer_V_0_3_4_fu_180 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_1_0_4_fu_184 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_0_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd0) & (trunc_ln25_reg_2103 == 2'd1))) begin
        buffer_V_1_0_4_fu_184 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_1_1_4_fu_188 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_1_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd1) & (trunc_ln25_reg_2103 == 2'd1))) begin
        buffer_V_1_1_4_fu_188 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_1_2_4_fu_192 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_2_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd2) & (trunc_ln25_reg_2103 == 2'd1))) begin
        buffer_V_1_2_4_fu_192 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_1_3_4_fu_196 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_1_3_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd3) & (trunc_ln25_reg_2103 == 2'd1))) begin
        buffer_V_1_3_4_fu_196 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_2_0_4_fu_200 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_0_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd0) & (trunc_ln25_reg_2103 == 2'd2))) begin
        buffer_V_2_0_4_fu_200 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_2_1_4_fu_204 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_1_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd1) & (trunc_ln25_reg_2103 == 2'd2))) begin
        buffer_V_2_1_4_fu_204 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_2_2_4_fu_208 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_2_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd2) & (trunc_ln25_reg_2103 == 2'd2))) begin
        buffer_V_2_2_4_fu_208 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_2_3_4_fu_212 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_2_3_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd3) & (trunc_ln25_reg_2103 == 2'd2))) begin
        buffer_V_2_3_4_fu_212 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_3_0_4_fu_216 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_0_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd0) & (trunc_ln25_reg_2103 == 2'd3))) begin
        buffer_V_3_0_4_fu_216 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_3_1_4_fu_220 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_1_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd1) & (trunc_ln25_reg_2103 == 2'd3))) begin
        buffer_V_3_1_4_fu_220 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_3_2_4_fu_224 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_2_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd2) & (trunc_ln25_reg_2103 == 2'd3))) begin
        buffer_V_3_2_4_fu_224 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer_V_3_3_4_fu_228 <= grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_buffer_V_3_3_1_out;
    end else if (((1'b1 == ap_CS_fsm_state6) & (empty_10_reg_2108 == 2'd3) & (trunc_ln25_reg_2103 == 2'd3))) begin
        buffer_V_3_3_4_fu_228 <= grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_160 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_fu_160 <= select_ln25_1_reg_2098;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten7_fu_164 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten7_fu_164 <= add_ln25_reg_2088;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_156 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        j_fu_156 <= add_ln26_fu_1384_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln25_reg_2088 <= add_ln25_fu_1136_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln25_fu_1130_p2 == 1'd0))) begin
        empty_10_reg_2108 <= empty_10_fu_1229_p1;
        select_ln25_1_reg_2098 <= select_ln25_1_fu_1216_p3;
        select_ln25_reg_2093 <= select_ln25_fu_1202_p3;
        tmp_reg_2113 <= tmp_fu_1246_p18;
        trunc_ln25_reg_2103 <= trunc_ln25_fu_1224_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd0) & (select_ln25_reg_2093 == 3'd0))) begin
        C_0_0_ap_vld = 1'b1;
    end else begin
        C_0_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd0) & (select_ln25_reg_2093 == 3'd1))) begin
        C_0_1_ap_vld = 1'b1;
    end else begin
        C_0_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd0) & (select_ln25_reg_2093 == 3'd2))) begin
        C_0_2_ap_vld = 1'b1;
    end else begin
        C_0_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_reg_2093 == 3'd0) & ~(select_ln25_reg_2093 == 3'd1) & ~(select_ln25_reg_2093 == 3'd2) & (1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd0))) begin
        C_0_3_ap_vld = 1'b1;
    end else begin
        C_0_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd1) & (select_ln25_reg_2093 == 3'd0))) begin
        C_1_0_ap_vld = 1'b1;
    end else begin
        C_1_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd1) & (select_ln25_reg_2093 == 3'd1))) begin
        C_1_1_ap_vld = 1'b1;
    end else begin
        C_1_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd1) & (select_ln25_reg_2093 == 3'd2))) begin
        C_1_2_ap_vld = 1'b1;
    end else begin
        C_1_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_reg_2093 == 3'd0) & ~(select_ln25_reg_2093 == 3'd1) & ~(select_ln25_reg_2093 == 3'd2) & (1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd1))) begin
        C_1_3_ap_vld = 1'b1;
    end else begin
        C_1_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd2) & (select_ln25_reg_2093 == 3'd0))) begin
        C_2_0_ap_vld = 1'b1;
    end else begin
        C_2_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd2) & (select_ln25_reg_2093 == 3'd1))) begin
        C_2_1_ap_vld = 1'b1;
    end else begin
        C_2_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd2) & (select_ln25_reg_2093 == 3'd2))) begin
        C_2_2_ap_vld = 1'b1;
    end else begin
        C_2_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_reg_2093 == 3'd0) & ~(select_ln25_reg_2093 == 3'd1) & ~(select_ln25_reg_2093 == 3'd2) & (1'b1 == ap_CS_fsm_state6) & (select_ln25_1_reg_2098 == 3'd2))) begin
        C_2_3_ap_vld = 1'b1;
    end else begin
        C_2_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_1_reg_2098 == 3'd0) & ~(select_ln25_1_reg_2098 == 3'd1) & ~(select_ln25_1_reg_2098 == 3'd2) & (1'b1 == ap_CS_fsm_state6) & (select_ln25_reg_2093 == 3'd0))) begin
        C_3_0_ap_vld = 1'b1;
    end else begin
        C_3_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_1_reg_2098 == 3'd0) & ~(select_ln25_1_reg_2098 == 3'd1) & ~(select_ln25_1_reg_2098 == 3'd2) & (1'b1 == ap_CS_fsm_state6) & (select_ln25_reg_2093 == 3'd1))) begin
        C_3_1_ap_vld = 1'b1;
    end else begin
        C_3_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_1_reg_2098 == 3'd0) & ~(select_ln25_1_reg_2098 == 3'd1) & ~(select_ln25_1_reg_2098 == 3'd2) & (1'b1 == ap_CS_fsm_state6) & (select_ln25_reg_2093 == 3'd2))) begin
        C_3_2_ap_vld = 1'b1;
    end else begin
        C_3_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln25_1_reg_2098 == 3'd0) & ~(select_ln25_1_reg_2098 == 3'd1) & ~(select_ln25_reg_2093 == 3'd0) & ~(select_ln25_reg_2093 == 3'd1) & ~(select_ln25_reg_2093 == 3'd2) & ~(select_ln25_1_reg_2098 == 3'd2) & (1'b1 == ap_CS_fsm_state6))) begin
        C_3_3_ap_vld = 1'b1;
    end else begin
        C_3_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln25_fu_1130_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln25_fu_1130_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln25_fu_1130_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_0_0 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_0_1 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_0_2 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_0_3 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_1_0 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_1_1 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_1_2 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_1_3 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_2_0 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_2_1 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_2_2 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_2_3 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_3_0 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_3_1 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_3_2 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign C_3_3 = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_buffer_V_3_0_out;

assign add_ln25_1_fu_1210_p2 = (i_fu_160 + 3'd1);

assign add_ln25_fu_1136_p2 = (indvar_flatten7_fu_164 + 5'd1);

assign add_ln26_fu_1384_p2 = (select_ln25_reg_2093 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign empty_10_fu_1229_p1 = select_ln25_fu_1202_p3[1:0];

assign grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start = grp_systolic_array_Pipeline_VITIS_LOOP_17_1_VITIS_LOOP_18_2_fu_732_ap_start_reg;

assign grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start = grp_systolic_array_Pipeline_VITIS_LOOP_27_5_fu_848_ap_start_reg;

assign icmp_ln25_fu_1130_p2 = ((indvar_flatten7_fu_164 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_1196_p2 = ((j_fu_156 == 3'd4) ? 1'b1 : 1'b0);

assign select_ln25_1_fu_1216_p3 = ((icmp_ln26_fu_1196_p2[0:0] == 1'b1) ? add_ln25_1_fu_1210_p2 : i_fu_160);

assign select_ln25_fu_1202_p3 = ((icmp_ln26_fu_1196_p2[0:0] == 1'b1) ? 3'd0 : j_fu_156);

assign tmp_3_fu_1234_p3 = {{trunc_ln25_fu_1224_p1}, {empty_10_fu_1229_p1}};

assign tmp_fu_1246_p17 = tmp_3_fu_1234_p3;

assign trunc_ln25_fu_1224_p1 = select_ln25_1_fu_1216_p3[1:0];

endmodule //systolic_array
